'use strict';
// Usage: node scripts/seed-recipes.js
// Populates the dev database with sample recipes for design evaluation.

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const USER_1 = 'cmlycl1np0000dnyoqbp04ipk'; // You
const USER_2 = 'cmlycl1up0001dnyolcqycxvm'; // Your girlfriend

const RECIPES = [
  {
    title: 'Spaghetti Carbonara',
    description: 'A classic Roman pasta dish — creamy, rich and deeply savory without a drop of cream. The secret is emulsifying the eggs with pasta water off the heat.',
    cuisine: 'Italian',
    madeOn: new Date('2025-11-12'),
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    authorId: USER_1,
    tags: ['dinner', 'quick', 'comfort'],
    ingredients: [
      { quantity: '200', unit: 'g', name: 'spaghetti' },
      { quantity: '150', unit: 'g', name: 'guanciale or pancetta, diced' },
      { quantity: '3', unit: '', name: 'egg yolks + 1 whole egg' },
      { quantity: '60', unit: 'g', name: 'Pecorino Romano, finely grated' },
      { quantity: '30', unit: 'g', name: 'Parmigiano Reggiano, grated' },
      { quantity: '', unit: '', name: 'black pepper, freshly ground' },
      { quantity: '', unit: '', name: 'salt' },
    ],
    steps: [
      'Bring a large pot of heavily salted water to a boil. Cook spaghetti 1 minute less than package directions.',
      'Meanwhile, cook guanciale in a cold dry pan over medium heat until golden and crispy, about 8 minutes. Remove from heat.',
      'In a bowl, whisk yolks, whole egg, Pecorino, and Parmigiano together with lots of black pepper.',
      'Reserve 1 cup of pasta water. Drain pasta and add to the pan with guanciale (off heat).',
      'Quickly add egg mixture, tossing constantly. Add pasta water a splash at a time to create a glossy, creamy sauce — not scrambled eggs.',
      'Serve immediately in warm bowls with extra cheese and pepper.',
    ],
  },
  {
    title: 'Chicken Tikka Masala',
    description: 'Tender marinated chicken in a fragrant, gently spiced tomato-cream sauce. Better than takeout and surprisingly straightforward to make.',
    cuisine: 'Indian',
    madeOn: new Date('2025-10-03'),
    prepTime: 30,
    cookTime: 40,
    servings: 4,
    authorId: USER_2,
    tags: ['dinner', 'comfort', 'weekend'],
    ingredients: [
      { quantity: '700', unit: 'g', name: 'chicken thighs, cut into chunks' },
      { quantity: '150', unit: 'g', name: 'full-fat yogurt' },
      { quantity: '2', unit: 'tbsp', name: 'tikka spice paste (or 2 tsp garam masala + 1 tsp cumin)' },
      { quantity: '2', unit: 'tbsp', name: 'vegetable oil' },
      { quantity: '2', unit: '', name: 'onions, finely sliced' },
      { quantity: '4', unit: '', name: 'garlic cloves, crushed' },
      { quantity: '1', unit: 'tbsp', name: 'fresh ginger, grated' },
      { quantity: '1', unit: 'tsp', name: 'ground coriander' },
      { quantity: '1', unit: 'tsp', name: 'cumin' },
      { quantity: '1', unit: 'tsp', name: 'smoked paprika' },
      { quantity: '400', unit: 'g', name: 'crushed tomatoes' },
      { quantity: '150', unit: 'ml', name: 'double cream' },
      { quantity: '1', unit: 'tsp', name: 'sugar' },
      { quantity: '', unit: '', name: 'fresh coriander, to serve' },
    ],
    steps: [
      'Marinate chicken in yogurt and tikka paste for at least 1 hour (overnight is better). Thread onto skewers and grill or broil until charred in spots, about 10 minutes.',
      'Heat oil in a large deep pan. Cook onions over medium-low heat for 15 minutes until very soft and golden.',
      'Add garlic, ginger, coriander, cumin, and paprika. Stir for 2 minutes until fragrant.',
      'Pour in crushed tomatoes, add sugar, season well. Simmer 15 minutes until the sauce thickens and deepens in color.',
      'Blend the sauce until smooth, or leave it chunky — your choice. Return to the pan.',
      'Add the grilled chicken pieces and double cream. Simmer gently for 10 minutes.',
      'Check seasoning and serve over basmati rice, scattered with fresh coriander.',
    ],
  },
  {
    title: 'Shakshuka',
    description: 'Eggs poached in a spiced tomato and pepper sauce — bright, satisfying, and on the table in 30 minutes. Excellent for a lazy weekend brunch.',
    cuisine: 'Middle Eastern',
    madeOn: new Date('2026-01-19'),
    prepTime: 10,
    cookTime: 25,
    servings: 2,
    authorId: USER_2,
    tags: ['breakfast', 'lunch', 'vegetarian', 'quick'],
    ingredients: [
      { quantity: '2', unit: 'tbsp', name: 'olive oil' },
      { quantity: '1', unit: '', name: 'red onion, finely chopped' },
      { quantity: '1', unit: '', name: 'red pepper, diced' },
      { quantity: '1', unit: '', name: 'yellow pepper, diced' },
      { quantity: '3', unit: '', name: 'garlic cloves, sliced' },
      { quantity: '1', unit: 'tsp', name: 'ground cumin' },
      { quantity: '1', unit: 'tsp', name: 'smoked paprika' },
      { quantity: '½', unit: 'tsp', name: 'chilli flakes' },
      { quantity: '400', unit: 'g', name: 'chopped tomatoes' },
      { quantity: '4', unit: '', name: 'eggs' },
      { quantity: '80', unit: 'g', name: 'feta, crumbled' },
      { quantity: '', unit: '', name: 'fresh flatbreads, to serve' },
      { quantity: '', unit: '', name: 'fresh parsley or coriander' },
    ],
    steps: [
      'Heat olive oil in a wide, deep frying pan over medium heat. Cook onion for 5 minutes until soft.',
      'Add peppers and cook another 5 minutes. Add garlic, cumin, paprika, and chilli — stir for 1 minute.',
      'Pour in tomatoes, season generously with salt and pepper. Simmer 10 minutes until the sauce thickens.',
      'Make 4 wells in the sauce with a spoon. Crack an egg into each well.',
      'Cover the pan and cook over low-medium heat for 6-8 minutes until whites are set but yolks are still runny.',
      'Scatter with feta and fresh herbs. Serve directly from the pan with warm flatbreads.',
    ],
  },
  {
    title: 'Chocolate Fondant',
    description: 'The ultimate dinner party dessert — crisp shell, molten dark chocolate center. Make the batter ahead; bake to order in 12 minutes.',
    cuisine: 'French',
    madeOn: new Date('2025-12-25'),
    prepTime: 20,
    cookTime: 12,
    servings: 4,
    authorId: USER_1,
    tags: ['dessert', 'elegant', 'weekend'],
    ingredients: [
      { quantity: '150', unit: 'g', name: 'dark chocolate (70%), chopped' },
      { quantity: '150', unit: 'g', name: 'unsalted butter + extra for greasing' },
      { quantity: '3', unit: '', name: 'whole eggs' },
      { quantity: '3', unit: '', name: 'egg yolks' },
      { quantity: '150', unit: 'g', name: 'caster sugar' },
      { quantity: '50', unit: 'g', name: 'plain flour' },
      { quantity: '', unit: '', name: 'cocoa powder, for dusting' },
      { quantity: '', unit: '', name: 'vanilla ice cream, to serve' },
    ],
    steps: [
      'Butter 4 ramekins generously and dust with cocoa powder. Refrigerate.',
      'Melt chocolate and butter together over a bain-marie or in the microwave in 30-second bursts. Stir smooth and let cool slightly.',
      'Whisk eggs, yolks, and sugar together vigorously for 3 minutes until pale and slightly thick.',
      'Fold the chocolate mixture into the eggs, then sift in the flour and fold gently until just combined.',
      'Pour into prepared ramekins. At this point they can be refrigerated for up to 24 hours.',
      'When ready to serve, preheat oven to 200°C. Bake straight from the fridge for 12-13 minutes — the edges should be set but the centre will still wobble.',
      'Run a knife around the edge, invert onto a warm plate, and serve immediately with ice cream.',
    ],
  },
  {
    title: 'Thai Green Curry',
    description: 'Fragrant, silky, and deeply aromatic — Thai green curry at home beats any restaurant version when you use a good paste and coconut cream.',
    cuisine: 'Thai',
    madeOn: new Date('2025-09-28'),
    prepTime: 15,
    cookTime: 25,
    servings: 3,
    authorId: USER_1,
    tags: ['dinner', 'spicy', 'quick'],
    ingredients: [
      { quantity: '2', unit: 'tbsp', name: 'green curry paste' },
      { quantity: '400', unit: 'ml', name: 'full-fat coconut cream' },
      { quantity: '500', unit: 'g', name: 'chicken breast or thigh, sliced' },
      { quantity: '200', unit: 'ml', name: 'chicken stock' },
      { quantity: '2', unit: 'tbsp', name: 'fish sauce' },
      { quantity: '1', unit: 'tbsp', name: 'palm sugar or brown sugar' },
      { quantity: '150', unit: 'g', name: 'green beans, trimmed' },
      { quantity: '1', unit: '', name: 'courgette, sliced' },
      { quantity: '6', unit: '', name: 'kaffir lime leaves, torn' },
      { quantity: '1', unit: 'stalk', name: 'lemongrass, bruised' },
      { quantity: '', unit: '', name: 'Thai basil and jasmine rice, to serve' },
    ],
    steps: [
      'Scoop the thick cream from the top of the coconut can into a wok or large pan. Heat over medium-high until it splits and sizzles.',
      'Add curry paste and fry in the coconut cream for 2 minutes, stirring constantly, until very fragrant.',
      'Add chicken and stir to coat. Cook for 3-4 minutes until sealed.',
      'Pour in remaining coconut cream, stock, fish sauce, sugar, lemongrass, and lime leaves. Simmer 10 minutes.',
      'Add vegetables and simmer 5 more minutes until just tender and the chicken is cooked through.',
      'Taste — balance with more fish sauce (salt), sugar, or lime juice. Remove lemongrass stalk.',
      'Serve over jasmine rice topped with Thai basil.',
    ],
  },
  {
    title: 'Classic Tiramisu',
    description: 'The no-bake Italian classic — mascarpone cream, espresso-soaked ladyfingers, and a generous dusting of bitter cocoa. Best made a day ahead.',
    cuisine: 'Italian',
    madeOn: new Date('2025-08-15'),
    prepTime: 30,
    cookTime: 0,
    servings: 6,
    authorId: USER_2,
    tags: ['dessert', 'noBake', 'party', 'makeAhead'],
    ingredients: [
      { quantity: '500', unit: 'g', name: 'mascarpone' },
      { quantity: '4', unit: '', name: 'eggs, separated' },
      { quantity: '100', unit: 'g', name: 'caster sugar' },
      { quantity: '300', unit: 'ml', name: 'strong espresso, cooled' },
      { quantity: '3', unit: 'tbsp', name: 'Marsala or dark rum' },
      { quantity: '200', unit: 'g', name: 'Savoiardi (ladyfinger biscuits)' },
      { quantity: '', unit: '', name: 'good quality cocoa powder, for dusting' },
    ],
    steps: [
      'Whisk egg yolks with sugar until pale, thick, and ribbon-like — about 3 minutes. Beat in mascarpone until smooth.',
      'In a clean bowl, whisk egg whites to stiff peaks. Fold gently into the mascarpone cream in three additions.',
      'Mix espresso with Marsala in a shallow bowl.',
      'Dip each ladyfinger briefly (1 second per side — do not soak) and arrange in a single layer in a 20×30 cm dish.',
      'Spread half the cream over the biscuit layer. Add a second layer of dipped ladyfingers. Top with remaining cream.',
      'Smooth the top, cover, and refrigerate for at least 4 hours — overnight is ideal.',
      'Just before serving, dust generously with cocoa powder through a fine sieve.',
    ],
  },
  {
    title: 'Sourdough Focaccia',
    description: 'Dimpled, olive oil-drenched, and impossibly airy. Using sourdough discard gives it a beautiful depth of flavor without needing much planning ahead.',
    cuisine: 'Italian',
    madeOn: new Date('2026-02-02'),
    prepTime: 20,
    cookTime: 25,
    servings: 8,
    authorId: USER_1,
    tags: ['baking', 'vegetarian', 'vegan', 'weekend'],
    ingredients: [
      { quantity: '500', unit: 'g', name: 'strong white bread flour' },
      { quantity: '375', unit: 'ml', name: 'warm water' },
      { quantity: '150', unit: 'g', name: 'sourdough discard (or 7g instant yeast)' },
      { quantity: '8', unit: 'g', name: 'salt' },
      { quantity: '80', unit: 'ml', name: 'good olive oil, divided' },
      { quantity: '4', unit: '', name: 'garlic cloves, thinly sliced' },
      { quantity: '', unit: '', name: 'flaky sea salt' },
      { quantity: '', unit: '', name: 'fresh rosemary sprigs' },
      { quantity: '', unit: '', name: 'cherry tomatoes (optional)' },
    ],
    steps: [
      'Mix flour, water, sourdough discard, and salt in a bowl. It will be a shaggy, sticky dough — that is correct.',
      'Drizzle 2 tbsp olive oil over the dough. Over the next 2 hours, perform 4 sets of stretch-and-folds every 30 minutes.',
      'Oil a high-sided baking tray generously with 3 tbsp olive oil. Transfer dough and stretch it gently to fill the tin. Cover and refrigerate overnight (or proof at room temperature for 4 hours).',
      'Remove from fridge 2 hours before baking. Drizzle with remaining olive oil.',
      'Preheat oven to 230°C. Oil your fingers and make deep dimples all over the dough. Press in rosemary, garlic, and tomatoes.',
      'Sprinkle with flaky salt. Bake 22-25 minutes until deeply golden.',
      'Drizzle with a little more olive oil as it comes out of the oven. Cool on a rack for 10 minutes before slicing.',
    ],
  },
  {
    title: 'Lemon Meringue Tart',
    description: 'A proper French patisserie-style lemon tart with crisp buttery pastry, intensely tangy curd, and a cloud of toasted meringue. Impressive but achievable.',
    cuisine: 'French',
    madeOn: new Date('2025-07-04'),
    prepTime: 60,
    cookTime: 40,
    servings: 8,
    authorId: USER_2,
    tags: ['dessert', 'baking', 'elegant'],
    ingredients: [
      { quantity: '200', unit: 'g', name: 'plain flour' },
      { quantity: '100', unit: 'g', name: 'cold butter, cubed' },
      { quantity: '2', unit: 'tbsp', name: 'icing sugar' },
      { quantity: '1', unit: '', name: 'egg yolk' },
      { quantity: '3', unit: 'tbsp', name: 'cold water' },
      { quantity: '3', unit: '', name: 'lemons, zest and juice (about 120ml juice)' },
      { quantity: '150', unit: 'g', name: 'caster sugar' },
      { quantity: '4', unit: '', name: 'whole eggs' },
      { quantity: '100', unit: 'g', name: 'cold butter, cubed (for curd)' },
      { quantity: '4', unit: '', name: 'egg whites' },
      { quantity: '200', unit: 'g', name: 'caster sugar (for meringue)' },
    ],
    steps: [
      'Make pastry: pulse flour, butter, and icing sugar until breadcrumbs. Add yolk and water, mix until it just comes together. Wrap and chill 30 minutes.',
      'Roll out pastry and line a 23cm tart tin. Chill another 20 minutes, then blind bake at 180°C for 15 minutes, remove weights, bake 10 more minutes until golden.',
      'Make curd: whisk lemon zest, juice, sugar, and eggs in a saucepan. Cook over medium-low heat, stirring constantly, until thick enough to coat the back of a spoon.',
      'Remove from heat, pass through a sieve, then stir in cold butter a few cubes at a time until glossy. Pour into the tart shell and chill until set, at least 2 hours.',
      'Make Italian meringue: heat 200g sugar with 60ml water to 121°C. Meanwhile whip egg whites to soft peaks. Stream hot syrup slowly into the whites while beating, then beat until cool and stiff.',
      'Pile meringue onto the tart and toast with a blowtorch or under a hot grill.',
    ],
  },
  {
    title: 'One-Pan Roasted Salmon',
    description: 'Weeknight dinner in 25 minutes — salmon fillets roasted on a bed of cherry tomatoes and capers with a lemony herb crust.',
    cuisine: 'Mediterranean',
    madeOn: new Date('2026-01-08'),
    prepTime: 10,
    cookTime: 18,
    servings: 2,
    authorId: USER_1,
    tags: ['dinner', 'healthy', 'quick'],
    ingredients: [
      { quantity: '2', unit: '', name: 'salmon fillets (150g each), skin on' },
      { quantity: '200', unit: 'g', name: 'cherry tomatoes, halved' },
      { quantity: '2', unit: 'tbsp', name: 'capers, drained' },
      { quantity: '3', unit: 'tbsp', name: 'olive oil' },
      { quantity: '1', unit: '', name: 'lemon, zest and juice' },
      { quantity: '2', unit: 'tbsp', name: 'panko breadcrumbs' },
      { quantity: '1', unit: 'tbsp', name: 'fresh dill or parsley, chopped' },
      { quantity: '2', unit: '', name: 'garlic cloves, crushed' },
      { quantity: '', unit: '', name: 'salt and black pepper' },
    ],
    steps: [
      'Preheat oven to 200°C. Toss cherry tomatoes, capers, 2 tbsp olive oil, and garlic in a roasting tin. Season and roast 5 minutes.',
      'Mix panko, lemon zest, dill, and remaining olive oil in a small bowl.',
      'Season salmon fillets well. Place skin-side down on the tomatoes. Press the panko crust onto the top of each fillet.',
      'Roast for 12-14 minutes until the crust is golden and the salmon is cooked through (or still slightly pink in the centre if you prefer).',
      'Squeeze lemon juice over everything and serve directly from the pan with crusty bread or a simple salad.',
    ],
  },
  {
    title: 'Beef & Mushroom Bourguignon',
    description: 'The great French braise — beef cooked low and slow in red wine with lardons, pearl onions, and mushrooms. A Sunday labour of love that rewards every minute.',
    cuisine: 'French',
    madeOn: new Date('2025-11-30'),
    prepTime: 40,
    cookTime: 180,
    servings: 6,
    authorId: USER_2,
    tags: ['dinner', 'comfort', 'weekend', 'makeAhead'],
    ingredients: [
      { quantity: '1.5', unit: 'kg', name: 'beef chuck or shin, cut into large cubes' },
      { quantity: '200', unit: 'g', name: 'lardons or thick-cut bacon' },
      { quantity: '1', unit: 'bottle', name: 'Burgundy or Pinot Noir' },
      { quantity: '300', unit: 'ml', name: 'beef stock' },
      { quantity: '200', unit: 'g', name: 'pearl onions, peeled' },
      { quantity: '300', unit: 'g', name: 'button mushrooms, quartered' },
      { quantity: '3', unit: '', name: 'carrots, cut into chunks' },
      { quantity: '3', unit: '', name: 'celery stalks, sliced' },
      { quantity: '4', unit: '', name: 'garlic cloves, crushed' },
      { quantity: '2', unit: 'tbsp', name: 'tomato paste' },
      { quantity: '2', unit: '', name: 'bay leaves' },
      { quantity: '4', unit: 'sprigs', name: 'fresh thyme' },
      { quantity: '2', unit: 'tbsp', name: 'plain flour' },
      { quantity: '3', unit: 'tbsp', name: 'olive oil' },
    ],
    steps: [
      'Optional: marinate the beef in wine overnight with the aromatics. Pat dry before cooking.',
      'Brown lardons in a large Dutch oven until crispy. Remove and set aside. Brown beef in batches in the fat — do not crowd the pan.',
      'Remove beef. Cook carrots, celery, and garlic until softened. Add tomato paste and flour, stir for 2 minutes.',
      'Pour in all the wine and stock, scraping up the brown bits. Add bay leaves and thyme. Return beef and lardons. The liquid should nearly cover the meat.',
      'Bring to a simmer, cover tightly, and cook in a 150°C oven for 2.5 to 3 hours until beef is completely tender.',
      'In the last 30 minutes, sauté pearl onions and mushrooms separately in butter until golden. Add to the pot.',
      'Taste and adjust seasoning. Serve over egg noodles, mash, or with crusty bread. It is even better the next day.',
    ],
  },
  {
    title: 'Japanese Miso Ramen',
    description: 'Rich tonkotsu-style broth with a miso tare, springy noodles, and all the toppings. This is a weekend project but every step is rewarding.',
    cuisine: 'Japanese',
    madeOn: new Date('2025-12-07'),
    prepTime: 45,
    cookTime: 240,
    servings: 4,
    authorId: USER_1,
    tags: ['dinner', 'comfort', 'weekend'],
    ingredients: [
      { quantity: '1', unit: 'kg', name: 'pork neck bones' },
      { quantity: '500', unit: 'g', name: 'pork belly, skin on' },
      { quantity: '4', unit: '', name: 'garlic cloves, smashed' },
      { quantity: '30', unit: 'g', name: 'fresh ginger, sliced' },
      { quantity: '3', unit: 'tbsp', name: 'white miso paste' },
      { quantity: '2', unit: 'tbsp', name: 'soy sauce' },
      { quantity: '1', unit: 'tbsp', name: 'mirin' },
      { quantity: '1', unit: 'tbsp', name: 'sesame oil' },
      { quantity: '400', unit: 'g', name: 'fresh ramen noodles' },
      { quantity: '4', unit: '', name: 'soft-boiled eggs, halved (marinated in soy)' },
      { quantity: '200', unit: 'g', name: 'corn kernels' },
      { quantity: '4', unit: '', name: 'spring onions, sliced' },
      { quantity: '1', unit: 'sheet', name: 'nori, cut into rectangles' },
      { quantity: '', unit: '', name: 'toasted sesame seeds' },
    ],
    steps: [
      'Blanch pork bones in boiling water for 5 minutes. Rinse under cold water and scrub clean.',
      'Place bones in a large pot with 3 litres water, garlic, and ginger. Bring to a rapid boil, then simmer hard for 4 hours, topping up with water as needed, until milky and rich.',
      'Meanwhile, cook pork belly: season, sear all sides, then braise in soy, mirin, and water for 1.5 hours until tender. Slice and set aside.',
      'Make miso tare: whisk miso, soy, mirin, and sesame oil together.',
      'Strain the broth, discarding solids. Season with salt — it should be well-seasoned.',
      'Cook ramen noodles according to package. Drain and divide between bowls.',
      'Ladle hot broth over noodles. Add a spoonful of miso tare to each bowl. Top with sliced pork belly, corn, spring onions, nori, eggs, and sesame seeds.',
    ],
  },
  {
    title: 'Banana Bread',
    description: 'The ideal use for very ripe bananas — a dense, moist loaf with a crackling sugared crust. Freezes beautifully; slice before freezing for easy grab-and-go breakfasts.',
    cuisine: 'American',
    madeOn: new Date('2026-02-10'),
    prepTime: 15,
    cookTime: 60,
    servings: 10,
    authorId: USER_2,
    tags: ['baking', 'breakfast', 'snack', 'vegetarian'],
    ingredients: [
      { quantity: '3', unit: '', name: 'very ripe bananas (about 300g peeled weight)' },
      { quantity: '80', unit: 'g', name: 'unsalted butter, melted' },
      { quantity: '150', unit: 'g', name: 'light brown sugar' },
      { quantity: '2', unit: '', name: 'eggs, beaten' },
      { quantity: '1', unit: 'tsp', name: 'vanilla extract' },
      { quantity: '200', unit: 'g', name: 'plain flour' },
      { quantity: '1', unit: 'tsp', name: 'baking soda' },
      { quantity: '½', unit: 'tsp', name: 'salt' },
      { quantity: '1', unit: 'tsp', name: 'cinnamon' },
      { quantity: '80', unit: 'g', name: 'walnuts or dark chocolate chips (optional)' },
      { quantity: '1', unit: 'tbsp', name: 'demerara sugar, for topping' },
    ],
    steps: [
      'Preheat oven to 175°C. Grease a 23×13 cm loaf tin and line with baking parchment.',
      'Mash bananas thoroughly in a large bowl — a few small lumps are fine.',
      'Stir in melted butter, then sugar, eggs, and vanilla.',
      'Sift in flour, baking soda, salt, and cinnamon. Fold until just combined — do not overmix.',
      'Fold in walnuts or chocolate chips if using. Pour into tin and smooth the top. Sprinkle with demerara sugar.',
      'Bake 55-65 minutes until a skewer inserted in the centre comes out clean. Cover loosely with foil after 40 minutes if the top is browning too fast.',
      'Cool in the tin for 10 minutes, then transfer to a wire rack. Best eaten slightly warm.',
    ],
  },
];

async function upsertTag(name) {
  return prisma.tag.upsert({
    where: { name },
    update: {},
    create: { name },
  });
}

async function main() {
  for (const recipe of RECIPES) {
    const { tags, ingredients, steps, authorId, ...recipeData } = recipe;

    // Upsert tags
    const tagRecords = await Promise.all(tags.map(upsertTag));

    const created = await prisma.recipe.create({
      data: {
        ...recipeData,
        authorId,
        tags: {
          create: tagRecords.map((tag) => ({ tagId: tag.id })),
        },
        ingredients: {
          create: ingredients.map((ing, i) => ({
            ...ing,
            order: i,
          })),
        },
        steps: {
          create: steps.map((instruction, i) => ({
            instruction,
            order: i + 1,
          })),
        },
      },
    });

    console.log(`Created: ${created.title}`);
  }
}

main()
  .then(() => console.log('\nDone! 12 recipes seeded.'))
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
